version: '3.2'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: app
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php_conf.ini
    networks:
      - tabela-nutricao

   #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - tabela-nutricao

  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'tabela'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './.docker/mysql:/var/lib/mysql'
    networks:
      - tabela-nutricao

networks:
  tabela-nutricao:
    driver: bridge
